/* Generated by cbindgen — do not edit manually. */

#ifndef CODETRACER_TRACE_WRITER_H
#define CODETRACER_TRACE_WRITER_H

/* Warning: this file is autogenerated by cbindgen. Do not modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event-log kind — mirrors [`EventLogKind`].
 */
typedef enum FfiEventLogKind {
    WRITE = 0,
    WRITE_FILE = 1,
    WRITE_OTHER = 2,
    READ = 3,
    READ_FILE = 4,
    READ_OTHER = 5,
    READ_DIR = 6,
    OPEN_DIR = 7,
    CLOSE_DIR = 8,
    SOCKET = 9,
    OPEN = 10,
    ERROR = 11,
    TRACE_LOG_EVENT = 12,
    EVM_EVENT = 13,
} FfiEventLogKind;

/**
 * Trace file format — mirrors [`TraceEventsFileFormat`].
 */
typedef enum FfiTraceFormat {
    JSON = 0,
    BINARY_V0 = 1,
    BINARY = 2,
} FfiTraceFormat;

/**
 * Type kind — mirrors [`TypeKind`] (subset used by the FFI).
 */
typedef enum FfiTypeKind {
    SEQ = 0,
    SET = 1,
    HASH_SET = 2,
    ORDERED_SET = 3,
    ARRAY = 4,
    VARARGS = 5,
    STRUCT = 6,
    INT = 7,
    FLOAT = 8,
    STRING = 9,
    C_STRING = 10,
    CHAR = 11,
    BOOL = 12,
    LITERAL = 13,
    REF = 14,
    RECURSION = 15,
    RAW = 16,
    ENUM = 17,
    ENUM16 = 18,
    ENUM32 = 19,
    C = 20,
    TABLE_KIND = 21,
    UNION = 22,
    POINTER = 23,
    ERROR = 24,
    FUNCTION_KIND = 25,
    TYPE_VALUE = 26,
    TUPLE = 27,
    VARIANT = 28,
    HTML = 29,
    NONE = 30,
    NON_EXPANDED = 31,
    ANY = 32,
    SLICE = 33,
} FfiTypeKind;

/**
 * Opaque handle passed across the FFI boundary.
 */
typedef struct TraceWriterHandle TraceWriterHandle;

/**
 * Retrieve the last error message for the current thread.
 *
 * Returns a pointer to a NUL-terminated UTF-8 string.  The pointer is valid
 * until the next FFI call **on the same thread**.  Returns an empty string
 * when no error has occurred.
 */
const char *trace_writer_last_error(void);

/**
 * Create a new trace writer.
 *
 * `program` is a NUL-terminated C string identifying the program being
 * traced.  `format` selects the on-disk serialisation format.
 *
 * Returns a heap-allocated handle that **must** be freed with
 * [`trace_writer_free`].  Returns `NULL` on failure (check
 * [`trace_writer_last_error`]).
 */
struct TraceWriterHandle *trace_writer_new(const char *program, enum FfiTraceFormat format);

/**
 * Free a trace writer handle.  Passing `NULL` is a no-op.
 */
void trace_writer_free(struct TraceWriterHandle *handle);

bool trace_writer_begin_metadata(struct TraceWriterHandle *handle, const char *path);

bool trace_writer_finish_metadata(struct TraceWriterHandle *handle);

bool trace_writer_begin_events(struct TraceWriterHandle *handle, const char *path);

bool trace_writer_finish_events(struct TraceWriterHandle *handle);

bool trace_writer_begin_paths(struct TraceWriterHandle *handle, const char *path);

bool trace_writer_finish_paths(struct TraceWriterHandle *handle);

void trace_writer_start(struct TraceWriterHandle *handle, const char *path, int64_t line);

/**
 * Override the working directory recorded in the trace metadata.
 *
 * By default the workdir is set to the process's current directory at
 * the time [`trace_writer_new`] is called.  Call this before
 * [`trace_writer_finish_metadata`] to record a different directory.
 */
void trace_writer_set_workdir(struct TraceWriterHandle *handle, const char *workdir);

void trace_writer_register_step(struct TraceWriterHandle *handle, const char *path, int64_t line);

/**
 * Register a function and return its ID.  Returns `usize::MAX` on error.
 */
uintptr_t trace_writer_ensure_function_id(struct TraceWriterHandle *handle,
                                          const char *name,
                                          const char *path,
                                          int64_t line);

/**
 * Register a type and return its ID.  Returns `usize::MAX` on error.
 */
uintptr_t trace_writer_ensure_type_id(struct TraceWriterHandle *handle,
                                      enum FfiTypeKind kind,
                                      const char *lang_type);

/**
 * Register a call to the function identified by `function_id`.
 *
 * For simplicity the FFI does not expose argument passing — call
 * `trace_writer_register_variable_with_full_value` for each arg before
 * this function.
 */
void trace_writer_register_call(struct TraceWriterHandle *handle, uintptr_t function_id);

/**
 * Register a function return with no explicit return value.
 */
void trace_writer_register_return(struct TraceWriterHandle *handle);

/**
 * Register a function return with an integer return value.
 */
void trace_writer_register_return_int(struct TraceWriterHandle *handle,
                                      int64_t value,
                                      enum FfiTypeKind type_kind,
                                      const char *type_name);

/**
 * Register a function return with a string (raw) return value.
 */
void trace_writer_register_return_raw(struct TraceWriterHandle *handle,
                                      const char *value_repr,
                                      enum FfiTypeKind type_kind,
                                      const char *type_name);

/**
 * Register a variable with an integer value.
 */
void trace_writer_register_variable_int(struct TraceWriterHandle *handle,
                                        const char *name,
                                        int64_t value,
                                        enum FfiTypeKind type_kind,
                                        const char *type_name);

/**
 * Register a variable with a string (raw) value representation.
 */
void trace_writer_register_variable_raw(struct TraceWriterHandle *handle,
                                        const char *name,
                                        const char *value_repr,
                                        enum FfiTypeKind type_kind,
                                        const char *type_name);

/**
 * Register an I/O or special event with optional metadata.
 *
 * `metadata` is an arbitrary NUL-terminated string attached to the event
 * (for example a file descriptor or channel name).  Pass `NULL` or an empty
 * string when no metadata is needed.
 */
void trace_writer_register_special_event(struct TraceWriterHandle *handle,
                                         enum FfiEventLogKind kind,
                                         const char *metadata,
                                         const char *content);

#endif  /* CODETRACER_TRACE_WRITER_H */
