/* Generated by cbindgen — do not edit manually. */

#ifndef CODETRACER_TRACE_WRITER_H
#define CODETRACER_TRACE_WRITER_H

/* Warning: this file is autogenerated by cbindgen. Do not modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Compounds nest at most this deep.
 */
#define MAX_NESTING_DEPTH 32

/**
 * The failure return of the path-id calls.
 */
#define CT_TW_INVALID_PATH_ID UINT64_MAX

typedef struct MetaDatReader MetaDatReader;

/**
 * The reader behind a `ct_reader_t`.
 */
typedef struct TraceReader TraceReader;

/**
 * The writer behind a `trace_writer_t`.
 */
typedef struct TraceWriterHandle TraceWriterHandle;

/**
 * The encoder behind a `value_encoder_t`.
 */
typedef struct ValueEncoder ValueEncoder;

/**
 * One file's transition across a reload, as the header lays it out.
 */
typedef struct CtTwSourceReloadChange {
    uint64_t old_path_id;
    uint64_t new_path_id;
    uint64_t generation;
} CtTwSourceReloadChange;

/**
 * This thread's last error: a NUL-terminated string, empty when no call has
 * reported one, valid until the next call on this thread.
 */
const char *trace_writer_last_error(void);

/**
 * Reset this thread's error buffer to the empty string.
 */
void trace_writer_clear_last_error(void);

/**
 * How this library was compiled, as `key:value` pairs joined by `;`. Static,
 * never NULL.
 */
const char *trace_writer_build_config(void);

/**
 * Initialize the library. Nothing needs initializing; the call exists so a
 * host written for the Nim library, which must call it first, links.
 */
void codetracer_trace_writer_init(void);

/**
 * The span records of the container at `path`, as a JSON array: settled
 * (last record wins, by span id) when `settled != 0`, else every record in
 * append order. NULL on failure, a container with no span stream included.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `out_len` is NULL or writable.
 */
uint8_t *ct_spans_json(const char *path, int32_t settled, uintptr_t *out_len);

/**
 * The span-type index of the container at `path`, as a JSON array of
 * `{"type_id","name","span_ids"}`. NULL on failure, a container with no
 * span-type index included.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `out_len` is NULL or writable.
 */
uint8_t *ct_span_types_json(const char *path, uintptr_t *out_len);

/**
 * `[{"position":P,"steps":[s,...]},...]` in position order; 1 when the
 * container keeps no line-hit index.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `out_buf` and `out_len` are NULL or
 * writable.
 */
int32_t ct_linehits_json(const char *path, uint8_t **out_buf, uintptr_t *out_len);

/**
 * Every correlation-index entry, in key order and bucket order; 1 when the
 * container is not indexed.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `out_buf` and `out_len` are NULL or
 * writable.
 */
int32_t ct_correlation_index_json(const char *path, uint8_t **out_buf, uintptr_t *out_len);

/**
 * The confirmed kind-0 entries for `(trace_id, span_id)`, wire bytes; 1
 * when the container is not indexed.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; both `(pointer, length)` pairs are
 * readable or NULL/0; `out_buf` and `out_len` are NULL or writable.
 */
int32_t ct_correlation_lookup_span(const char *path,
                                   const uint8_t *trace_id,
                                   uintptr_t trace_id_len,
                                   const uint8_t *span_id,
                                   uintptr_t span_id_len,
                                   uint8_t **out_buf,
                                   uintptr_t *out_len);

/**
 * The confirmed kind-1 entries for `(marker_id, key_value)`; 1 when the
 * container is not indexed.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `(key_value, key_value_len)` is readable
 * or NULL/0; `out_buf` and `out_len` are NULL or writable.
 */
int32_t ct_correlation_lookup_boundary(const char *path,
                                       uint64_t marker_id,
                                       const uint8_t *key_value,
                                       uintptr_t key_value_len,
                                       uint8_t **out_buf,
                                       uintptr_t *out_len);

/**
 * The marker labels in id order, each as the lowercase hex of its bytes; 1
 * when the container declares no marker.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `out_buf` and `out_len` are NULL or
 * writable.
 */
int32_t ct_marker_labels_json(const char *path, uint8_t **out_buf, uintptr_t *out_len);

/**
 * Encode a version 6 `meta.dat` into a buffer the caller releases with
 * [`ct_free_buffer`]. A NULL or empty `recording_id` mints one.
 *
 * # Safety
 * Every `(pointer, length)` pair is readable or NULL/0; `args` and
 * `arg_lens` hold `args_count` entries; `out_buf` and `out_len` are writable.
 */
int32_t ct_write_meta_dat_to_buffer(const uint8_t *program,
                                    uintptr_t program_len,
                                    const uint8_t *workdir,
                                    uintptr_t workdir_len,
                                    const uint8_t *const *args,
                                    const uintptr_t *arg_lens,
                                    uintptr_t args_count,
                                    const uint8_t *recorder_id,
                                    uintptr_t recorder_id_len,
                                    const uint8_t *recording_id,
                                    uintptr_t recording_id_len,
                                    uint8_t **out_buf,
                                    uintptr_t *out_len);

/**
 * Release a buffer this library handed out. NULL is a no-op.
 *
 * # Safety
 * `buf` is NULL or a buffer this library returned and not yet released.
 */
void ct_free_buffer(uint8_t *buf);

/**
 * Decode a `meta.dat`. NULL on failure.
 *
 * # Safety
 * `(data, len)` is readable or NULL/0.
 */
struct MetaDatReader *ct_read_meta_dat(const uint8_t *data, uintptr_t len);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_len` is NULL or writable.
 */
const uint8_t *ct_meta_dat_program(struct MetaDatReader *h, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_len` is NULL or writable.
 */
const uint8_t *ct_meta_dat_workdir(struct MetaDatReader *h, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_len` is NULL or writable.
 */
const uint8_t *ct_meta_dat_recorder_id(struct MetaDatReader *h, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_len` is NULL or writable.
 */
const uint8_t *ct_meta_dat_recording_id(struct MetaDatReader *h, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader.
 */
uintptr_t ct_meta_dat_args_count(struct MetaDatReader *h);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_len` is NULL or writable.
 */
const uint8_t *ct_meta_dat_arg(struct MetaDatReader *h, uintptr_t idx, uintptr_t *out_len);

/**
 * 1 when the `meta.dat` carries a filter-provenance block, else 0.
 *
 * # Safety
 * `h` is NULL or a live `meta.dat` reader.
 */
int32_t ct_meta_dat_has_filter_provenance(struct MetaDatReader *h);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader.
 */
uintptr_t ct_meta_dat_filter_provenance_count(struct MetaDatReader *h);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_len` is NULL or writable.
 */
const uint8_t *ct_meta_dat_filter_provenance_path(struct MetaDatReader *h,
                                                  uintptr_t idx,
                                                  uintptr_t *out_len);

/**
 * Copy the 32-byte digest of filter-provenance entry `idx` to `out_buf`. 0 on
 * success.
 *
 * # Safety
 * `h` is NULL or a live `meta.dat` reader; `out_buf` is NULL or 32 writable
 * bytes.
 */
int32_t ct_meta_dat_filter_provenance_sha256(struct MetaDatReader *h,
                                             uintptr_t idx,
                                             uint8_t *out_buf);

/**
 * # Safety
 * `h` is NULL or a live `meta.dat` reader, not used afterwards.
 */
void ct_meta_dat_free(struct MetaDatReader *h);

/**
 * Write a new, empty container at `path`; `block_size` 0 is 4096.
 *
 * # Safety
 * `path` is NULL or NUL-terminated.
 */
int32_t ct_container_create(const char *path, uint32_t block_size);

/**
 * Append `count` internal files to the closed container at `path`, as one
 * batch: a name already present, or repeated, refuses the whole batch.
 *
 * # Safety
 * `path` is NULL or NUL-terminated; `names`, `contents` and `lengths` hold
 * `count` entries (or are NULL when `count` is 0); `contents[i]` holds
 * `lengths[i]` readable bytes or is NULL when that is 0.
 */
int32_t ct_container_append_files(const char *path,
                                  const char *const *names,
                                  const uint8_t *const *contents,
                                  const uintptr_t *lengths,
                                  uintptr_t count);

/**
 * # Safety
 * `path` is NULL or NUL-terminated.
 */
struct TraceReader *ct_reader_open(const char *path);

/**
 * # Safety
 * `path` is NULL or NUL-terminated.
 */
struct TraceReader *ct_reader_open_assume_column_aware_paths(const char *path);

/**
 * # Safety
 * `(data, len)` is readable or NULL/0.
 */
struct TraceReader *ct_reader_open_bytes(const uint8_t *data, uintptr_t len);

/**
 * Re-read the container at `path` into `h`. On failure `h` is unchanged.
 *
 * # Safety
 * `h` is NULL or a live reader; `path` is NULL or NUL-terminated.
 */
int32_t ct_reader_refresh(struct TraceReader *h, const char *path);

/**
 * # Safety
 * `h` is NULL or a live reader, not used afterwards.
 */
void ct_reader_close(struct TraceReader *h);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_path(struct TraceReader *h, uint64_t id, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_function(struct TraceReader *h, uint64_t id, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_type_name(struct TraceReader *h, uint64_t id, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_varname(struct TraceReader *h, uint64_t id, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_program(struct TraceReader *h, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_workdir(struct TraceReader *h, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_step(struct TraceReader *h, uint64_t n, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_values(struct TraceReader *h, uint64_t n, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_call(struct TraceReader *h, uint64_t key, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_call_for_step(struct TraceReader *h, uint64_t step_id, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_len` is NULL or writable.
 */
uint8_t *ct_reader_event(struct TraceReader *h, uint64_t index, uintptr_t *out_len);

/**
 * # Safety
 * `h` is NULL or a live reader; the out pointers are NULL or writable.
 */
int32_t ct_reader_step_location(struct TraceReader *h,
                                uint64_t n,
                                uint64_t *out_path_id,
                                uint64_t *out_line);

/**
 * # Safety
 * `h` is NULL or a live reader; the out buffers hold `count` entries.
 */
uint64_t ct_reader_step_locations(struct TraceReader *h,
                                  uint64_t start_n,
                                  uint64_t count,
                                  uint64_t *out_path_ids,
                                  uint64_t *out_lines);

/**
 * # Safety
 * `h` is NULL or a live reader; the out buffers hold `count` entries.
 */
uint64_t ct_reader_step_locations_with_columns(struct TraceReader *h,
                                               uint64_t start_n,
                                               uint64_t count,
                                               uint64_t *out_path_ids,
                                               uint64_t *out_lines,
                                               uint64_t *out_columns);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_glis` holds `count` entries.
 */
uint64_t ct_reader_step_global_line_indices(struct TraceReader *h,
                                            uint64_t start_n,
                                            uint64_t count,
                                            uint64_t *out_glis);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_value` is NULL or writable.
 */
int32_t ct_reader_line_length(struct TraceReader *h,
                              uint64_t file_id,
                              uint32_t line_index0,
                              uint32_t *out_value);

/**
 * # Safety
 * `h` is NULL or a live reader; `out_value` is NULL or writable.
 */
int32_t ct_reader_line_length_raw(struct TraceReader *h,
                                  uint64_t file_id,
                                  uint32_t line_index0,
                                  uint32_t *out_value);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
uint64_t ct_reader_line_count_raw(struct TraceReader *h, uint64_t file_id);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
int32_t ct_reader_path_table_kind(struct TraceReader *h, uint64_t file_id);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
int32_t ct_reader_has_column_aware_steps(struct TraceReader *h);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
int32_t ct_reader_column_aware_paths_suspected(struct TraceReader *h);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
int32_t ct_reader_supports_column_breakpoints(struct TraceReader *h);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
int32_t ct_reader_supports_column_motions(struct TraceReader *h);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
uint64_t ct_reader_step_value_count(struct TraceReader *h, uint64_t n);

/**
 * # Safety
 * `h` is NULL or a live reader; the out pointers are NULL or writable.
 */
int32_t ct_reader_step_value(struct TraceReader *h,
                             uint64_t n,
                             uint64_t value_idx,
                             uint64_t *out_varname_id,
                             uint64_t *out_type_id,
                             uint8_t **out_data,
                             uintptr_t *out_data_len);

/**
 * # Safety
 * `h` is NULL or a live reader; the out pointers are NULL or writable.
 */
int32_t ct_reader_call_fields(struct TraceReader *h,
                              uint64_t key,
                              uint64_t *out_function_id,
                              int64_t *out_parent_key,
                              uint64_t *out_entry_step,
                              uint64_t *out_exit_step,
                              uint32_t *out_depth,
                              uint64_t *out_children_count);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
uint64_t ct_reader_call_child(struct TraceReader *h, uint64_t key, uint64_t child_idx);

/**
 * # Safety
 * `h` is NULL or a live reader.
 */
uint64_t ct_reader_call_arg_count(struct TraceReader *h, uint64_t key);

/**
 * # Safety
 * `h` is NULL or a live reader; the out pointers are NULL or writable.
 */
int32_t ct_reader_call_arg(struct TraceReader *h,
                           uint64_t key,
                           uint64_t arg_idx,
                           uint64_t *out_varname_id,
                           uint8_t **out_data,
                           uintptr_t *out_data_len);

/**
 * # Safety
 * `h` is NULL or a live reader; the out pointers are NULL or writable.
 */
int32_t ct_reader_event_fields(struct TraceReader *h,
                               uint64_t index,
                               uint8_t *out_kind,
                               uint64_t *out_step_id,
                               uint8_t **out_data,
                               uintptr_t *out_data_len);

/**
 * # Safety
 * `h` is NULL or a live reader; the out pointers are NULL or writable.
 */
int32_t ct_reader_event_metadata(struct TraceReader *h,
                                 uint64_t index,
                                 uint8_t **out_data,
                                 uintptr_t *out_data_len);

struct ValueEncoder *ct_value_encoder_new(void);

/**
 * # Safety
 * `h` is NULL or an encoder `ct_value_encoder_new` returned, not yet freed.
 */
void ct_value_encoder_free(struct ValueEncoder *h);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
void ct_value_encoder_reset(struct ValueEncoder *h);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_int(struct ValueEncoder *h, int64_t value, uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_float(struct ValueEncoder *h, double value, uint64_t type_id);

/**
 * A bool with type id 0.
 *
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_bool(struct ValueEncoder *h, int32_t value);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_bool_typed(struct ValueEncoder *h, int32_t value, uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder; `(data, len)` is readable or NULL/0.
 */
int32_t ct_value_write_string(struct ValueEncoder *h,
                              const uint8_t *data,
                              uintptr_t len,
                              uint64_t type_id);

/**
 * A None with type id 0.
 *
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_none(struct ValueEncoder *h);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_none_typed(struct ValueEncoder *h, uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder; `(data, len)` is readable or NULL/0.
 */
int32_t ct_value_write_raw(struct ValueEncoder *h,
                           const uint8_t *data,
                           uintptr_t len,
                           uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder; `(data, len)` is readable or NULL/0.
 */
int32_t ct_value_write_error(struct ValueEncoder *h,
                             const uint8_t *data,
                             uintptr_t len,
                             uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_begin_struct(struct ValueEncoder *h, uint64_t type_id, int32_t field_count);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_begin_sequence(struct ValueEncoder *h, uint64_t type_id, int32_t element_count);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_begin_sequence_with_slice(struct ValueEncoder *h,
                                           uint64_t type_id,
                                           int32_t element_count,
                                           int32_t is_slice);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_begin_tuple(struct ValueEncoder *h, uint64_t type_id, int32_t element_count);

/**
 * # Safety
 * `h` is NULL or a live encoder; `(discriminator, disc_len)` is readable or
 * NULL/0.
 */
int32_t ct_value_begin_variant(struct ValueEncoder *h,
                               const uint8_t *discriminator,
                               uintptr_t disc_len,
                               uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_begin_reference(struct ValueEncoder *h,
                                 uint64_t address,
                                 int32_t mutable_,
                                 uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_end_compound(struct ValueEncoder *h);

/**
 * A character: the low byte of `codepoint`, as a one-byte text string.
 *
 * # Safety
 * `h` is NULL or a live encoder.
 */
int32_t ct_value_write_char(struct ValueEncoder *h, uint32_t codepoint, uint64_t type_id);

/**
 * # Safety
 * `h` is NULL or a live encoder; `(data, len)` is readable or NULL/0.
 */
int32_t ct_value_write_bigint(struct ValueEncoder *h,
                              const uint8_t *data,
                              uintptr_t len,
                              int32_t negative,
                              uint64_t type_id);

/**
 * The bytes encoded so far, valid until the next call on the encoder; NULL
 * when there are none.
 *
 * # Safety
 * `h` is NULL or a live encoder; `out_len` is NULL or writable.
 */
const uint8_t *ct_value_get_bytes(struct ValueEncoder *h, uintptr_t *out_len);

/**
 * Create a writer. `format` must be 2 (`FFI_TRACE_FORMAT_BINARY`), the
 * split-stream container; any other is refused, naming it.
 *
 * # Safety
 * `program` is NULL or NUL-terminated.
 */
struct TraceWriterHandle *trace_writer_new(const char *program, int32_t format);

/**
 * Free a writer, finishing its container first when it was not closed.
 *
 * # Safety
 * `handle` is NULL or a writer not yet freed, not used afterwards.
 */
void trace_writer_free(struct TraceWriterHandle *handle);

/**
 * Close the writer: write the buffered step and what is held, and finish
 * the container. 0 on success; non-zero when the close failed or an earlier
 * call's failure was held.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_close(struct TraceWriterHandle *handle);

/**
 * The metadata and paths are written into the container; these succeed on
 * any handle and exist so a host written for separate files links.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_begin_metadata(struct TraceWriterHandle *handle, const char *_path);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_finish_metadata(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_begin_paths(struct TraceWriterHandle *handle, const char *_path);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_finish_paths(struct TraceWriterHandle *handle);

/**
 * Open the container at `<dir of path>/<program stem>.ct`. A writer already
 * open on a file is left as it is; one open in memory is refused.
 *
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
int32_t trace_writer_begin_events(struct TraceWriterHandle *handle, const char *path);

/**
 * Open the container in memory; after the close its bytes are read with
 * `trace_writer_container_ptr` / `_len`.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_begin_in_memory(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_finish_events(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
uintptr_t trace_writer_container_len(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_container_ready(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
uint8_t *trace_writer_container_ptr(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_set_compact_threshold(struct TraceWriterHandle *handle, uint64_t raw_bytes);

/**
 * # Safety
 * `handle` is NULL or a live writer; `recording_id` is NULL or
 * NUL-terminated.
 */
int32_t trace_writer_set_recording_id(struct TraceWriterHandle *handle, const char *recording_id);

/**
 * # Safety
 * `handle` is NULL or a live writer; `workdir` is NULL or NUL-terminated.
 */
void trace_writer_set_workdir(struct TraceWriterHandle *handle, const char *workdir);

/**
 * Record the program's arguments in `meta.dat`.
 *
 * # Safety
 * `handle` is NULL or a live writer; `args` and `arg_lens` hold `args_count`
 * entries, each `(args[i], arg_lens[i])` readable or NULL/0.
 */
void trace_writer_set_args(struct TraceWriterHandle *handle,
                           const uint8_t *const *args,
                           const uintptr_t *arg_lens,
                           uintptr_t args_count);

/**
 * Stamp a producer namespace on every interned string. Only the empty
 * qualifier — bare payloads, as a standalone recording has — is written by
 * this library; a writer open with another is refused.
 *
 * # Safety
 * `handle` is NULL or a live writer; `qualifier` is NULL or NUL-terminated.
 */
void trace_writer_set_interning_qualifier(struct TraceWriterHandle *handle, const char *qualifier);

/**
 * # Safety
 * `handle` is NULL or a live writer; every string is NULL or
 * NUL-terminated; `hook_strategies` holds `hook_strategies_count` strings.
 */
int32_t trace_writer_set_mcr_fields(struct TraceWriterHandle *handle,
                                    int32_t tick_source,
                                    uint32_t total_threads,
                                    int32_t atomic_mode,
                                    uint64_t total_events,
                                    uint32_t total_checkpoints,
                                    uint64_t start_time_unix_us,
                                    const char *platform,
                                    const char *tick_granularity,
                                    const char *tick_source_str,
                                    const char *atomic_mode_str,
                                    const char *start_time_str,
                                    const char *hook_profile,
                                    const char *const *hook_strategies,
                                    uintptr_t hook_strategies_count);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_set_replay_launch_fields(struct TraceWriterHandle *handle,
                                              int32_t aslr_disabled);

/**
 * # Safety
 * `handle` is NULL or a live writer; `(fingerprint, fingerprint_len)` is
 * readable or NULL/0.
 */
int32_t trace_writer_set_layout_snapshot(struct TraceWriterHandle *handle,
                                         uint64_t layout_hash,
                                         const uint8_t *fingerprint,
                                         uintptr_t fingerprint_len);

/**
 * Record one trace-filter file in the filter-provenance block.
 *
 * # Safety
 * `handle` is NULL or a live writer; both `(pointer, length)` pairs are
 * readable or NULL/0.
 */
int32_t trace_writer_add_filter_provenance(struct TraceWriterHandle *handle,
                                           const uint8_t *path,
                                           uintptr_t path_len,
                                           const uint8_t *sha256,
                                           uintptr_t sha256_len);

/**
 * Record that the recorder implements trace filters and its chain is empty.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_record_empty_filter_provenance(struct TraceWriterHandle *handle);

/**
 * `meta.dat` is written by the container's first record; this succeeds on a
 * begun container writer.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t ct_write_meta_dat(struct TraceWriterHandle *handle,
                          const uint8_t *_recorder_id,
                          uintptr_t _recorder_id_len);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_declare_source_reload(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_enable_column_aware_steps(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_enable_column_breakpoints_support(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_enable_column_motions_support(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_enable_line_count_table(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
int32_t trace_writer_register_path_with_line_count(struct TraceWriterHandle *handle,
                                                   const char *path,
                                                   uint64_t line_count);

/**
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated; when
 * `line_count > 0`, `line_lengths` is NULL or holds that many entries.
 */
int32_t trace_writer_register_path_with_line_lengths(struct TraceWriterHandle *handle,
                                                     const char *path,
                                                     int32_t line_count,
                                                     const uint32_t *line_lengths);

/**
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
uint64_t trace_writer_register_path_version(struct TraceWriterHandle *handle,
                                            const char *path,
                                            uint64_t line_count);

/**
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
uint64_t trace_writer_current_path_id(struct TraceWriterHandle *handle, const char *path);

/**
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
uint64_t trace_writer_register_path(struct TraceWriterHandle *handle, const char *path);

/**
 * # Safety
 * `handle` is NULL or a live writer; `name` is NULL or NUL-terminated.
 */
uint64_t trace_writer_register_variable_name(struct TraceWriterHandle *handle, const char *name);

/**
 * # Safety
 * `handle` is NULL or a live writer; `changed` holds `changed_count`
 * entries.
 */
uint64_t trace_writer_register_source_reload(struct TraceWriterHandle *handle,
                                             const struct CtTwSourceReloadChange *changed,
                                             uintptr_t changed_count,
                                             uint64_t in_flight_frames);

/**
 * Buffer an alternate source view of the registered path `path_id`; its
 * 0-based index, or -1 on failure.
 *
 * # Safety
 * `handle` is NULL or a live writer; each `(pointer, length)` pair is
 * readable or NULL/0.
 */
int64_t trace_writer_register_source_view(struct TraceWriterHandle *handle,
                                          uint64_t path_id,
                                          uint8_t view_kind,
                                          const char *view_name,
                                          uintptr_t view_name_len,
                                          const uint8_t *content,
                                          uintptr_t content_len,
                                          const uint8_t *sourcemap,
                                          uintptr_t sourcemap_len);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
uint64_t trace_writer_source_reload_count(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
uint64_t trace_writer_next_step_index(struct TraceWriterHandle *handle);

/**
 * The `<toplevel>` function, its call, and the entry step.
 *
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
void trace_writer_start(struct TraceWriterHandle *handle, const char *path, int64_t line);

/**
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
void trace_writer_register_step(struct TraceWriterHandle *handle, const char *path, int64_t line);

/**
 * A step at `(path, line)`; a column is not carried by this entry point,
 * and asking for one is reported.
 *
 * # Safety
 * `handle` is NULL or a live writer; `path` is NULL or NUL-terminated.
 */
void ct_assignment_with_column(struct TraceWriterHandle *handle,
                               const char *path,
                               int64_t line,
                               int64_t _column,
                               int32_t has_column);

/**
 * Move the buffered step's column by `column_delta`; with no step buffered,
 * a column step of its own.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_delta_column(struct TraceWriterHandle *handle, int64_t column_delta);

/**
 * # Safety
 * `handle` is NULL or a live writer; `name` and `path` are NULL or
 * NUL-terminated.
 */
uintptr_t trace_writer_ensure_function_id(struct TraceWriterHandle *handle,
                                          const char *name,
                                          const char *path,
                                          int64_t line);

/**
 * # Safety
 * `handle` is NULL or a live writer; `lang_type` is NULL or NUL-terminated.
 */
uintptr_t trace_writer_ensure_type_id(struct TraceWriterHandle *handle,
                                      int32_t kind,
                                      const char *lang_type);

/**
 * Stage one argument of the next call: its name and encoded value.
 *
 * # Safety
 * `handle` is NULL or a live writer; `name` is NULL or NUL-terminated;
 * `(cbor_data, cbor_len)` is readable or NULL/0.
 */
void trace_writer_register_call_arg(struct TraceWriterHandle *handle,
                                    const char *name,
                                    const uint8_t *cbor_data,
                                    uintptr_t cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_call(struct TraceWriterHandle *handle, uintptr_t function_id);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_return(struct TraceWriterHandle *handle);

/**
 * # Safety
 * `handle` is NULL or a live writer; `type_name` is NULL or NUL-terminated.
 */
void trace_writer_register_return_int(struct TraceWriterHandle *handle,
                                      int64_t value,
                                      int32_t type_kind,
                                      const char *type_name);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_return_int_by_type_id(struct TraceWriterHandle *handle,
                                                 int64_t value,
                                                 uintptr_t type_id);

/**
 * # Safety
 * `handle` is NULL or a live writer; `value_repr` and `type_name` are NULL
 * or NUL-terminated.
 */
void trace_writer_register_return_raw(struct TraceWriterHandle *handle,
                                      const char *value_repr,
                                      int32_t type_kind,
                                      const char *type_name);

/**
 * A return whose value is already encoded; an empty value is no value.
 *
 * # Safety
 * `handle` is NULL or a live writer; `(cbor_data, cbor_len)` is readable or
 * NULL/0.
 */
void trace_writer_register_return_cbor(struct TraceWriterHandle *handle,
                                       const uint8_t *cbor_data,
                                       uintptr_t cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer; the strings are NULL or NUL-terminated.
 */
void trace_writer_register_variable_int(struct TraceWriterHandle *handle,
                                        const char *name,
                                        int64_t value,
                                        int32_t type_kind,
                                        const char *type_name);

/**
 * # Safety
 * `handle` is NULL or a live writer; `name` is NULL or NUL-terminated.
 */
void trace_writer_register_variable_int_by_type_id(struct TraceWriterHandle *handle,
                                                   const char *name,
                                                   int64_t value,
                                                   uintptr_t type_id);

/**
 * # Safety
 * `handle` is NULL or a live writer; the strings are NULL or NUL-terminated.
 */
void trace_writer_register_variable_raw(struct TraceWriterHandle *handle,
                                        const char *name,
                                        const char *value_repr,
                                        int32_t type_kind,
                                        const char *type_name);

/**
 * # Safety
 * `handle` is NULL or a live writer; the strings are NULL or NUL-terminated.
 */
void trace_writer_register_variable_raw_by_type_id(struct TraceWriterHandle *handle,
                                                   const char *name,
                                                   const char *value_repr,
                                                   uintptr_t type_id);

/**
 * A variable whose value is already encoded, stored verbatim.
 *
 * # Safety
 * `handle` is NULL or a live writer; `name` is NULL or NUL-terminated;
 * `(cbor_data, cbor_len)` is readable or NULL/0.
 */
void trace_writer_register_variable_cbor(struct TraceWriterHandle *handle,
                                         const char *name,
                                         const uint8_t *cbor_data,
                                         uintptr_t cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer; `target_name` is NULL or
 * NUL-terminated; `(rvalue_cbor, rvalue_cbor_len)` is readable or NULL/0.
 */
int32_t trace_writer_register_assignment(struct TraceWriterHandle *handle,
                                         const char *target_name,
                                         uint8_t pass_by,
                                         const uint8_t *rvalue_cbor,
                                         uintptr_t rvalue_cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer; `names` holds `count` strings, each NULL
 * or NUL-terminated (`names` may be NULL when `count` is 0).
 */
int32_t trace_writer_register_drop_variables(struct TraceWriterHandle *handle,
                                             const char *const *names,
                                             uintptr_t count);

/**
 * # Safety
 * `handle` is NULL or a live writer; `name` is NULL or NUL-terminated.
 */
int32_t trace_writer_register_drop_variable(struct TraceWriterHandle *handle, const char *name);

/**
 * # Safety
 * `handle` is NULL or a live writer; `variable_name` is NULL or
 * NUL-terminated.
 */
int32_t trace_writer_bind_variable(struct TraceWriterHandle *handle,
                                   const char *variable_name,
                                   int64_t place);

/**
 * # Safety
 * `handle` is NULL or a live writer; `variable_name` is NULL or
 * NUL-terminated.
 */
int32_t trace_writer_register_variable_cell(struct TraceWriterHandle *handle,
                                            const char *variable_name,
                                            int64_t place);

/**
 * # Safety
 * `handle` is NULL or a live writer; `(value_cbor, value_cbor_len)` is
 * readable or NULL/0.
 */
int32_t trace_writer_register_cell_value(struct TraceWriterHandle *handle,
                                         int64_t place,
                                         const uint8_t *value_cbor,
                                         uintptr_t value_cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer; `(value_cbor, value_cbor_len)` is
 * readable or NULL/0.
 */
int32_t trace_writer_register_compound_value(struct TraceWriterHandle *handle,
                                             int64_t place,
                                             const uint8_t *value_cbor,
                                             uintptr_t value_cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer; `(new_value_cbor, new_value_cbor_len)`
 * is readable or NULL/0.
 */
int32_t trace_writer_assign_cell(struct TraceWriterHandle *handle,
                                 int64_t place,
                                 const uint8_t *new_value_cbor,
                                 uintptr_t new_value_cbor_len);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_assign_compound_item(struct TraceWriterHandle *handle,
                                          int64_t place,
                                          uint64_t index,
                                          int64_t item_place);

/**
 * `BindVariable` for a host with no use for the failure value.
 *
 * # Safety
 * `handle` is NULL or a live writer; `variable_name` is NULL or
 * NUL-terminated.
 */
void ct_bind_variable(struct TraceWriterHandle *handle, const char *variable_name, int64_t place);

/**
 * An assignment whose right-hand side is given by kind and operands.
 *
 * # Safety
 * `handle` is NULL or a live writer; the strings are NULL or NUL-terminated;
 * `compound_ids` holds `compound_len` entries or is NULL.
 */
void ct_assignment(struct TraceWriterHandle *handle,
                   const char *target_name,
                   int32_t pass_by,
                   int32_t rvalue_kind,
                   uintptr_t simple_variable_id,
                   const uintptr_t *compound_ids,
                   uintptr_t compound_len,
                   const char *field_name,
                   int64_t index,
                   int64_t call_key);

/**
 * `kind` is the event's `EventLogKind` ordinal (0-13); another value is
 * refused.
 *
 * # Safety
 * `handle` is NULL or a live writer; `metadata` and `content` are NULL or
 * NUL-terminated.
 */
void trace_writer_register_special_event(struct TraceWriterHandle *handle,
                                         int32_t kind,
                                         const char *metadata,
                                         const char *content);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_thread_start(struct TraceWriterHandle *handle, uint64_t thread_id);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_thread_exit(struct TraceWriterHandle *handle, uint64_t thread_id);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_thread_switch(struct TraceWriterHandle *handle, uint64_t thread_id);

/**
 * # Safety
 * `handle` is NULL or a live writer; `(message, message_len)` is readable or
 * NULL/0.
 */
void trace_writer_register_raise(struct TraceWriterHandle *handle,
                                 uint64_t exception_type_id,
                                 const uint8_t *message,
                                 uintptr_t message_len);

/**
 * # Safety
 * `handle` is NULL or a live writer.
 */
void trace_writer_register_catch(struct TraceWriterHandle *handle, uint64_t exception_type_id);

/**
 * The innermost call exits by an exception: `exception_len` (> 0) bytes of
 * CBOR, recorded verbatim as its call record's `exception`.
 *
 * # Safety
 * `handle` is NULL or a live writer; `(exception_cbor, exception_len)` is
 * readable or NULL/0.
 */
void trace_writer_register_return_exception(struct TraceWriterHandle *handle,
                                            const uint8_t *exception_cbor,
                                            uintptr_t exception_len);

/**
 * Append a span record. 0 on success.
 *
 * # Safety
 * `handle` is NULL or a live writer; the strings are NULL or NUL-terminated;
 * `metadata_keys` and `metadata_values` hold `metadata_count` strings each.
 */
int32_t trace_writer_register_span(struct TraceWriterHandle *handle,
                                   uint64_t span_id,
                                   uint64_t parent_span_id,
                                   uint8_t flags,
                                   uint8_t status,
                                   uint64_t start_wall_ns,
                                   uint64_t end_wall_ns,
                                   uint64_t process_ord,
                                   uint64_t thread_id,
                                   uint64_t start_step,
                                   uint64_t end_step,
                                   const char *external_recording,
                                   const char *external_path,
                                   const char *span_type,
                                   const char *label,
                                   uint8_t structural,
                                   const char *const *metadata_keys,
                                   const char *const *metadata_values,
                                   uintptr_t metadata_count);

/**
 * Seal the current partial span chunk. 0 on success, and on a writer that
 * has not begun.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_flush_spans(struct TraceWriterHandle *handle);

/**
 * Open a crossing span and return its span id; 0 on failure.
 *
 * # Safety
 * `handle` is NULL or a live writer; `span_type` is NULL or NUL-terminated.
 */
uint64_t trace_writer_begin_crossing(struct TraceWriterHandle *handle, const char *span_type);

/**
 * Settle the innermost open crossing, `span_id`. 0 on success.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_end_crossing(struct TraceWriterHandle *handle, uint64_t span_id);

/**
 * Intern a marker label and write its id to `*out_id`. 0 on success; a
 * refusal returns 1 without a message.
 *
 * # Safety
 * `handle` is NULL or a live writer; `(label, label_len)` is readable or
 * NULL/0; `out_id` is NULL or writable.
 */
int32_t trace_writer_ensure_marker_id(struct TraceWriterHandle *handle,
                                      const uint8_t *label,
                                      uintptr_t label_len,
                                      uint64_t *out_id);

/**
 * Declare a boundary crossing against an interned label id. 0 on success; a
 * refusal returns 1 without a message.
 *
 * # Safety
 * `handle` is NULL or a live writer; each `(pointer, length)` pair is
 * readable or NULL/0.
 */
int32_t trace_writer_mark_correlation_by_id(struct TraceWriterHandle *handle,
                                            uint64_t marker_id,
                                            const uint8_t *boundary_label,
                                            uintptr_t boundary_label_len,
                                            const uint8_t *direction,
                                            uintptr_t direction_len,
                                            const uint8_t *key_value,
                                            uintptr_t key_value_len,
                                            const uint8_t *show_value,
                                            uintptr_t show_value_len,
                                            const uint8_t *description,
                                            uintptr_t description_len,
                                            const uint8_t *key_text,
                                            uintptr_t key_text_len,
                                            const uint8_t *show_text,
                                            uintptr_t show_text_len);

/**
 * Intern `boundary_id` and declare a boundary crossing against it.
 *
 * # Safety
 * As [`trace_writer_mark_correlation_by_id`].
 */
int32_t trace_writer_mark_correlation(struct TraceWriterHandle *handle,
                                      const uint8_t *direction,
                                      uintptr_t direction_len,
                                      const uint8_t *boundary_id,
                                      uintptr_t boundary_id_len,
                                      const uint8_t *key_value,
                                      uintptr_t key_value_len,
                                      const uint8_t *show_value,
                                      uintptr_t show_value_len,
                                      const uint8_t *description,
                                      uintptr_t description_len,
                                      const uint8_t *key_text,
                                      uintptr_t key_text_len,
                                      const uint8_t *show_text,
                                      uintptr_t show_text_len);

/**
 * Declare that the recording covers `(trace_id, span_id)`, given as wire
 * bytes. 0 on success.
 *
 * # Safety
 * `handle` is NULL or a live writer; both `(pointer, length)` pairs are
 * readable.
 */
int32_t trace_writer_mark_span_coverage(struct TraceWriterHandle *handle,
                                        const uint8_t *trace_id,
                                        uintptr_t trace_id_len,
                                        const uint8_t *span_id,
                                        uintptr_t span_id_len,
                                        uint64_t wall_time_unix_ns,
                                        uint64_t monotonic_time_ns);

/**
 * [`trace_writer_mark_span_coverage`] with the ids in hex: 32 and 16 hex
 * characters, either case.
 *
 * # Safety
 * `handle` is NULL or a live writer; both `(pointer, length)` pairs are
 * readable or NULL/0.
 */
int32_t trace_writer_mark_span_coverage_hex(struct TraceWriterHandle *handle,
                                            const uint8_t *trace_id_hex,
                                            uintptr_t trace_id_hex_len,
                                            const uint8_t *span_id_hex,
                                            uintptr_t span_id_hex_len,
                                            uint64_t wall_time_unix_ns,
                                            uint64_t monotonic_time_ns);

/**
 * Keep a `linehits.tc` index from now on, the buffered step included. 0 on
 * success.
 *
 * # Safety
 * `handle` is NULL or a live writer.
 */
int32_t trace_writer_enable_linehits(struct TraceWriterHandle *handle);

#endif  /* CODETRACER_TRACE_WRITER_H */
