name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install capnproto
      run: sudo apt-get install -y capnproto
    - name: Lint
      run: cargo clippy

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install capnproto
      run: sudo apt-get install -y capnproto
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
