name: Rust

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install capnproto
      run: sudo apt-get install -y capnproto
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Lint
      run: just lint

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install capnproto
      run: sudo apt-get install -y capnproto
    - name: Install just
      uses: extractions/setup-just@v2
    - name: Build
      run: just build
    - name: Run tests
      run: just test
