name: Windows Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Install capnproto
        shell: pwsh
        run: choco install capnproto -y
      - name: Test
        shell: bash
        run: cargo test
